### ISSUE TITLE
subject/content

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/emailobfuscator#11]
wenn an die zu vernebelnde emailadresse ein ?subject oder ?content angehängt sind funktioniert die enschlüsslung nicht mehr:

 `mailto:friends@redaxo.org?subject=freebeer`  erzeugt im emailprogramm  `friends@redaxo.org&`

**Comment by schuer** [comment]
Ich arbeite gerade an PRs, kann den Fix hier gerne mit übernehmen.

**Comment by schuer** [comment]
Es ist leider komplizierter als vermutet, denn man kann auch solche Dinge machen:

``` html
<a href="mailto:john.doe@example.com.tld?cc=someoneelse@theirsite.com, another@thatsite.com&bcc=lastperson@theirsite.com&subject=Big%20News&body=Lorem%20ipsum">john.doe@example.com.tld</a>
```

Besonders problematisch ist, dass durch CC und BCC weitere `@` hineinkommen, und damit rechnet der Parser — abgesehen von den oben genannten Issues — aktuell gar nicht.

Ich denke, wir könnten es halbwegs einfach dadurch fixen, dass die Regex den gesamten String am ersten `@` aufsplittet. Aber mal sehen…

**Comment by schuer** [comment]
Anders gelöst: Es wird _alles_ nach `mailto:` verschlüsselt. Und zwar mittels ROT13-Transformation, weil das wohl nach wie vor sehr sicher ist und vermeidet, dass versehentlich Anführungsstriche reinrutschen, die das HTML durcheinander bringen würden.

Das Hardcore-Beispiel oben funktioniert damit nun auch problemlos, denn letztendlich ist jetzt total egal, was alles ins mailto gesteckt wird.
