### ISSUE TITLE
UI-Elemente vereinheitlichen (Buttons, Alerts)

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/emailobfuscator#12]
- Footer, Button (Position, Beschriftung)
- Alerts (Position, Farbe)

![emailobfuscator_01](https://cloud.githubusercontent.com/assets/1297466/18128536/8f8dbaf4-6f86-11e6-9313-3d9593be1c9f.jpg)

**Comment by phoebusryan** [comment]
Klingt gut. Machst du das direkt bei allen Addons ? :P
