### ISSUE TITLE
Assets (CSS, JS) automatisch laden [optional]

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/emailobfuscator#13]
Styles und Scripts müssen zur Zeit noch manuell ins Template eingebracht werden. Ich fände es klasse, wenn das Addon sich automatisch darum kümmern könnte. Damit müsste das Addon nur installiert werden, und die Verschlüsselung würde sofort auf der Website greifen.

Allerdings sollte es eine Möglichkeit geben, das automatische Laden der Assets zu unterbinden, für den Fall, dass sie in bestehende Ressourcen gemerget werden sollen(, was natürlich performanter und schöner ist).

Anpassungen:
- 2 Checkboxen (CSS und JS) auf der Settings-Page im Backend, per default aktiviert
- Autoload CSS per `rex_view::addCssFile`
- Autoload JS per `rex_view::addJsFile` ist leider problematisch, weil jQuery benötigt wird. Deshalb entweder prüfen, ob jQuery bereits hinzugefügt wurde oder aber das Addon JS unmittelbar vorm schließenden `</body>` einfügen.
- Hinweis auf Autoload in der README ergänzen
- Hinweis auf jQuery in der README ergänzen

**Comment by phoebusryan** [comment]
Den Gedanken hatte ich auch schon. Man könnte auch den EP OUTPUT_FILTER nutzen. rex_view ist ja primär fürs Backend soviel ich weiss. Der Autoload ist auch wegen der Abwärtskompatiblität problematisch weil dann das File zweimal geladen wird.

Bzgl. jQuery ... ja hm. Grundsätzlich könnte man das Snippet auch kurz auf Vanilla umbauen. Wäre kein grosses Ding.

**Comment by schuer** [comment]
Mittels OUTPUT_FILTER umgesetzt wie oben genannt. CSS vor den schließenden `</head>` und JS vor den schließenden `</body>`.

jQuery-Abhängigkeit habe ich jetzt erstmal gelassen, kann gerne später nochmal angefasst werden.
