### ISSUE TITLE
CSS: Unicorn-Styles robuster machen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/emailobfuscator#14]
Das Unicorn kommt aktuell als `<span class="unicorn">_at_</span>`, mittels CSS kommt ein `@` davor und die Breite wird auf `1em` beschnitten. Das ist nicht sonderlich robust, denn je nach Font ist ein @-Zeichen nicht immer 1em breit, und dann sieht man Artefakte des nachfolgenden `_at_`.

Ich schlage vor, das Unicorn auf `<span class="unicorn"><span>_at_</span></span>` anzupassen, dann kann das innere `_at_` sehr einfach komplett ausgeblendet werden, und es ist kein zusätzliches Styling mehr notwendig.

**Comment by phoebusryan** [comment]
Full ack; war damals ein Schnellschuss aber hat seitdem keine Probleme gemacht. Dein Vorschlag ist aber natürlich schöner.
