### ISSUE TITLE
Whitelist Email in der Konfiguration ergänzen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/emailobfuscator#16]
Aktuell gibt es die Funktion `rex_emailobfuscator::whitelistEmail();`. Wenn wir sowieso schon Artikel und Templates auf der Konfigurationsseite im Backend whitelisten können, wäre es vielleicht sinnvoll, auch die E-Mailadressen dort zu ergänzen, damit es einheitlich bleibt?

**Comment by phoebusryan** [comment]
Nein, diese Funktion ist für die Dynamik im Frontend. Zum Beispiel für einen Loginbereich oder sowas. Die Methode muss bleiben und hat auf jeden Fall ihre Daseinsberechtigung.

**Comment by schuer** [comment]
Okay, na dann lassen wir das.
