### ISSUE TITLE
Option nur für mailto

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/emailobfuscator#20]
Würde das Problem lösen, dass E-Mail-Adressen an ungewollter Stelle ersetzt werden. 
Im Normalfall werden E-Mail-Adressen immer mit einem Mailto-Link veröffentlicht.

**Comment by phoebusryan** [comment]
Das wäre grundsätzlich denkbar, jedoch ist dies mit dem POST-Filter und der Whiteliste auch schon abgedeckt. Es würde aber unter Umständen Arbeit abnehmen. Hm..

**Comment by phoebusryan** [comment]
Ist eingebaut in Version 2.1.0
