### ISSUE TITLE
Fehler bei clean install

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/emailobfuscator#21]
"ErrorException" thrown in /var/www/dev2/redaxo/src/addons/emailobfuscator/boot.php on line 16
Fatal error: Call to a member function getTemplateId() on a non-object

Wenn nagelneues REDAXO (ohne Startartikel ausgewählt)

Möglicher Fix line 16: 
if ( !is_null(rex_article::getCurrent()) && ...

**Comment by phoebusryan** [comment]
Wann tritt der Fehler genau auf? Im Frontend?

**Comment by tyrant88** [comment]
sorry, Ja im Frontend.
Wenn man es fixed, erscheint dann die übliche Meldung "kein Startartikel ausgewählt" .

**Comment by phoebusryan** [comment]
Danke, ich schaus mir an
