### ISSUE TITLE
Vorbelegte Formularfelder werden gesichert, sollten aber nicht

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/emailobfuscator#25]
Siehe https://github.com/yakamara/redaxo_ycom/issues/174#issuecomment-346786966.
Wenn z.B. YCom ein Feld mit einer E-Mailadresse vorbelegt wird auch diese abgesichert. Allerdings sollte `value="ich@meinedomain.de"` nicht verschlüsselt werden.

**Comment by phoebusryan** [comment]
Dafür gibts die Whitelist: https://github.com/FriendsOfREDAXO/emailobfuscator/blob/master/lib/class.emailobfuscator.php#L7-L10 oder die Möglichkeit nur Emailadresse mit mailto: davor zu verschlüsseln (zu finden in den Addon-Einstellungen).
