### ISSUE TITLE
boot.php - automatisches Einbinden v. css/js ist vertauscht

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/emailobfuscator#26]
M.E. fehlt in der **boot.php** in den Zeilen 28 u. 34 jeweils ein "**!**".
Anstatt
`if ($this->getConfig('autoload_css')) {`
müsste es in Zeile 28 heissen:
`if (!$this->getConfig('autoload_css')) {`
und in Zeile 34 dementsprechend
`if (!$this->getConfig('autoload_js')) {`

Ansonsten ist das automatische Einbinden der Resourcen genau vertauscht, d.h. wenn keine Häkchen gesetzt sind, werden sie automatisch eingebunden und wenn welche gesetzt sind, werden sie nicht eingebunden.

**Comment by phoebusryan** [comment]
Nein, wenn das Häckchen gesetzt ist, wirds eingebunden. Gesetzt ist es nach der Installation automatisch.

**Comment by greatif** [comment]
Hab ich vllt. missverständlich formuliert:
Ich habe Emailobfuscator installiert und die Häkchen sind dann auch gesetzt. (Alles unverändert gelassen, keine Ausnahmen definiert.) Die Verschlüsselung greift jedoch nicht. Trotz der standardmäßig gesetzten Häkchen sind die E-Mail-Adressen klar. Klicke ich die Häkchen raus, werden die E-Mail-Adressen verschlüsselt.
Am AddOn geändert hab ich nix.

**Comment by phoebusryan** [comment]
Dünkt mich doch sehr komisch. Kannst du mir mal einen Testlink + Zugang schicken? Am besten via Slack.

**Comment by phoebusryan** [comment]
Geklärt in Slack; deshalb closed.
