### ISSUE TITLE
pipe `|`statt @im mailto: Link? 

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/emailobfuscator#27]
![zwischenablage-1](https://user-images.githubusercontent.com/1277494/37141344-fe887b96-22b4-11e8-8705-280930887c09.jpg)

Da stand auch was als letzter Kommentar ("wegen W3C"?) beim letzten Update...?

**Comment by phoebusryan** [comment]
Das ist richtig. Müsstest evtl. das Asset aktualisieren. W3C hat das encodete @ nicht erlaubt und hat einen Fehler geworfen. Mit der Pipe klappts wunderbar.

**Comment by tyrant88** [comment]
Ich steh auf'm Schlauch. Bei mir klappt es eben nicht. Was soll ich tun?
![zwischenablage-1](https://user-images.githubusercontent.com/1277494/37142521-a3191a32-22b8-11e8-986e-32a053dfe4bf.jpg)

**Comment by phoebusryan** [comment]
Uff, da ist in der Tat noch ein Fehler drin bzw etwas, was ich nicht committed habe. Habs nun grade noch published. Es geht um die JS Datei die hier nicht aktuell war. Danke fürs mitteilen.

**Comment by tyrant88** [comment]
alles klar. Danke.

**Comment by isospin** [comment]
z.zt. (2.1.4) ersetzt die js datei immer noch das hash zeichen anstatt das pipe zeichen...
bzw. wurde die änderung rückgängig gemacht 25a5236

**Comment by phoebusryan** [comment]
In der letzten Version war ein Fehler drin. Deshalb habe ich ein neues Release gemacht. Pipe gibts nicht mehr. Nur noch Hash. Das ganze hat nicht so funktioniert wie ich es wollte und ich habs zu schnell released gehabt..

**Comment by isospin** [comment]
bei mir sieht es nach einem update auf 2.1.4. genauso aus wie bei norbert oben.

wenn ich 25a5236 ODER b1e1e9c  rückgängig mache geht es.
oder anders gesagt in der php datei wird das '@' durch ein '|' ersetzt und in der  js datei ein '#' durch ein '@' - das passt nicht zusammen bzw. ist gerade nicht synchron.

**Comment by phoebusryan** [comment]
Ich habe da wohl grade ein Chaos drin. Speziell wie das passiert ist. Danke für den PR. So funktionierts nun erstmal wieder.
