### ISSUE TITLE
Bitte neues Release veröffentlichen

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/emailobfuscator#29]
Der emailobfuscator ist zur Zeit nicht nutzbar und muss manuell auf allen Installationen gepatcht werden obwohl die Version im Git funktioniert. Bitte ein Bugfix Release veröffentlichen.

**Comment by schuer** [comment]
[2.1.5](https://github.com/FriendsOfREDAXO/emailobfuscator/releases/tag/2.1.5) ist jetzt im Installer.

(Ich hab’s mal übernommen, weil @phoebusryan gerade andere Dinge zu tun hat außerhalb des Webs. 🎉 )

**Comment by TobiasKrais** [comment]
Danke!
