### ISSUE TITLE
Json-String invalid, wenn darin E-Mail-Adressen verschlüsselt werden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/emailobfuscator#31]

**Comment by phoebusryan** [comment]
Wo hast du denn JSON-Strings? Das Addon greift via Outputfilter.

**Comment by tbaddade** [comment]
Im Frontend werden in einem data-Attribute via Json Daten weitergereicht.

**Comment by phoebusryan** [comment]
Achso. Speziell. In dem Falle kannst du die Emailadresse whitelisten (siehe Methoden), da sie ohnehin Plain übertragen wird.

**Comment by tbaddade** [comment]
> In dem Falle kannst du die Emailadresse whitelisten

Ist leider keine Lösung, wenn die Adressen verschleiert werden sollen.

Habe jetzt in der `boot.php` vom project-Addon folgendes 
```php
if (!rex::isBackend() && rex_addon::get('emailobfuscator')->isAvailable()) {
    rex_extension::register('OUTPUT_FILTER', function (rex_extension_point $ep) {
        $subject = $ep->getSubject();
        $subject = preg_replace_callback('/(\\\\&quot;)mailto:(.*?)(?=\\\\&quot;&gt;)/', function($matches) {
            $json = $matches[1] == '\&quot;' ? true : false;
            $mail = $matches[2];
            $mail = str_rot13($mail); // ROT13-Transformation
            $mail = str_replace('@', '|', $mail); // Ersetze @ durch |, um E-Mailadressen von weiteren RegEx auszuschließen
            $return = 'javascript:decryptUnicorn(' . $mail . ')';
            // dump('>'.$mail.'<');
            return $json ? $matches[1].htmlspecialchars_decode($return) : $matches[1].$return;

        }, $subject);
        $ep->setSubject($subject);
    }, rex_extension::EARLY);
}
```

Ist zwar speziell, aber eventuell eine Basis für das AddOn.

**Comment by TobiasKrais** [comment]
@tbaddade: ich kenne mich mit JSON nicht so gut aus und auch nicht mit Regulären Ausdrücken. Kannst du mir ein Codebeispiel liefert, dann einfach nur herausfindet ob die E-Mailadresse in einem Regulären Ausdruck vorhanden ist? Dann könnte ich das integrieren.

**Comment by tbaddade** [comment]
Ich verstehe nicht ganz was du jetzt genau haben willst. Ich muss dazu sagen, dass das obige auch eher selten auftritt. Im JsonString waren E-Mail-Adressen die durch das Aden "verschlüsselt" wurden. Dadurch wurde aber wieder der Json-String invalid.

Ich müsste noch mal das Projekt heraussuchen, wo genau das der Fall war.

**Comment by TobiasKrais** [comment]
Ich brauche ein Codebeispiel, das mit nur sagt, ob sich die E-Mailadresse in einem JSON String befindet oder nicht. Es sollte ein TRUE oder FALSE am Ende herauskommen. Weißt du was ich meine?

**Comment by tbaddade** [comment]
Ich schließe. @TobiasKrais Wenn du noch Hilfe benötigst dann gern anderer Stelle.
