### ISSUE TITLE
Wunschliste: Kategorie ausschließen

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/emailobfuscator#4]
Ich fände es praktisch, wenn man Kategorien, oder besser noch Templates, ausschließen könnte, wenn z.B. der entsprechende Artikel als Newsletter verschickt wird. 
lg

**Comment by phoebusryan** [comment]
Danke für das Issue. Werde ich in Kürze umsetzen.

**Comment by TrueHatori** [comment]
Könnte man eventuell auch einzelne Artikel ausschließen? Z.B. die, in welcher man das eigene Profil ändern kann? Im Moment müssen die User, wenn sie ihre E-Mail ändern wollen, mir Bescheid geben. Die Adresse im Formular leer zu lassen, sieht blöd aus wenn alle anderen schon ausgefüllt sind, aber die auch ausfüllen geht leider nicht. Mir ist die Verschlüsselung aber wichtiger als das Formular. Sicher, man könnte drum proggen, aber ich frag erstmal, ob das machbar ist ;)

**Comment by phoebusryan** [comment]
@TrueHatori Das wäre grundsätzlich auch eine Überlegung wert. In deinem Fall kannst du aber auch einfach folgendes machen:

rex_emailobfuscator::whitelistEmail($email) ... irgendwo vor der Ausgabe des Formulares. Dann wird die Mailadresse nicht verschlüsselt und dein Problem wäre auch gelöst.

**Comment by phoebusryan** [comment]
Ich habe das ganze einfach mal eingebaut. Damit ist dieses Issue erledigt.
