### ISSUE TITLE
Addon wirft Warnungen

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/emailobfuscator#6]
> Warning: in_array() expects parameter 2 to be array, null given in /blubb/redaxo/src/addons/rex_emailobfuscator/boot.php on line 8

**Comment by tbaddade** [comment]
https://github.com/FriendsOfREDAXO/rex_emailobfuscator/blob/master/boot.php#L5-L6

Als default ein `[]` angeben

**Comment by phoebusryan** [comment]
Oh, danke. Fixe ich asap. Bin grad unterwegs.
