### ISSUE TITLE
Warnung wenn kein Artikel in Konfiguration ausgeschlossen wird

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/emailobfuscator#7]
Redaxo 5.2
E-Mailverschlüsselung: 1.3.0

Wenn kein Artikel in Konfiguration ausgeschlossen wird erfolgt folgender Fehler:
Warning: in_array() expects parameter 2 to be array, string given in /redaxo/src/addons/rex_emailobfuscator/boot.php on line 13

**Comment by phoebusryan** [comment]
Hm, wann tritt die Meldung auf? Ich habe diese nicht.

**Comment by TobiasKrais** [comment]
Hi Thomas,

schau dir mal die Webseite an: http://promitec.design-to-use.de/. 
Benutzername und Passwort sind "test". Der Fehler tritt immer auf, auf 
jeder Unterseite.

Wenn du Zugangsdaten brauchst, kannst du dich über meine Webseite an 
mich wenden: http://www.design-to-use.de

LG,

Tobi

**Comment by phoebusryan** [comment]
Ich sehe da keine Fehler auf den Seiten..?

**Comment by TobiasKrais** [comment]
Hi Thomas,

das ist sehr seltsam. Wo du es sagst, habe ich mal andere Browser getestet. Im Firefox und Chromium funktioniert es bei mir auch ohne Fehler. Nur im Google Chrome hat er eine Reihe Fehler:
Warning: in_array() expects parameter 2 to be array, string given in /promitec/redaxo/src/addons/rex_emailobfuscator/boot.php on line 13
Warning: Cannot modify header information - headers already sent by (output started at /promitec/redaxo/src/core/lib/error_handler.php:118) in /promitec/redaxo/src/core/lib/response.php on line 214
Warning: Cannot modify header information - headers already sent by (output started at /promitec/redaxo/src/core/lib/error_handler.php:118) in /promitec/redaxo/src/core/lib/response.php on line 223
Warning: Cannot modify header information - headers already sent by (output started at /promitec/redaxo/src/core/lib/error_handler.php:118) in /promitec/redaxo/src/core/lib/response.php on line 269
Warning: Cannot modify header information - headers already sent by (output started at /promitec/redaxo/src/core/lib/error_handler.php:118) in /promitec/redaxo/src/core/lib/response.php on line 311
Warning: Cannot modify header information - headers already sent by (output started at /promitec/redaxo/src/core/lib/error_handler.php:118) in /promitec/redaxo/src/core/lib/response.php on line 185
Warning: Cannot modify header information - headers already sent by (output started at /promitec/redaxo/src/core/lib/error_handler.php:118) in /promitec/redaxo/src/core/lib/response.php on line 188
��Xmo�6�����u6I...

Sobald ich im Addon unter Artikel ausschlißen hinzufüge ist der Fehler weg. Es kann also auch nicht am meinem Cache liegen. Kannst du mit Chrome den Fehler nachvollziehen?

Liebe Grüße,

Tobi

**Comment by phoebusryan** [comment]
Die Fehler hängen zusammen. Ist es Chrome auf Windows? Ich arbeite grundsätzlich mit Chrome/Mac, hätte aber auch einen Windowsrechner mit Chrome zur Verfügung.

**Comment by TobiasKrais** [comment]
Es ist Chrome auf Ubuntu Linux.

**Comment by phoebusryan** [comment]
Eigentlich komisch - die Fehler die da ausgespuckt werden, sind grundsätzlich serverseitig und sollten wenn schon Browserunabhängig sein. Ich schau mir das trotzdem mal im Detail an. Warst du jeweils eingeloggt als der Fehler auftrat? Das ist nämlich sicher noch ein relevanter Punkt.

**Comment by TobiasKrais** [comment]
Hi Thomas,

das mit dem Login ist ein Super Tipp. Der Fehler kommt nur wenn ich in Redaxo eingeloggt bin.

Liebe Grüße,

Tobi

**Comment by ceekay82** [comment]
Das Verhalten kann ich mit Windows 8.1 und Chrome nachvollziehen.

**Comment by phoebusryan** [comment]
Danke für eine zweite Meinung. Ich werde in dem Fall mal das ganze auf Windows/Chrome noch durchtesten. Ist sicher nur ein kleiner Fehler.

**Comment by TobiasKrais** [comment]
Der Fehler tritt nicht nur in Chrome auf. In allen Browsern, wenn man in Redaxo eingeloggt ist.

**Comment by phoebusryan** [comment]
Jep. Wie gesagt, ich werde der Sache asap nachgehen. Ich bin mir sicher, ich kann diese Woche noch ein Update bereitstellen.

**Comment by phoebusryan** [comment]
Könnt ihr mal bitte den Inhalt der boot.php mit dem nachfolgenden ersetzen und prüfen ob es damit klappt?

https://github.com/FriendsOfREDAXO/rex_emailobfuscator/blob/master/boot.php

**Comment by TobiasKrais** [comment]
Hi Thomas, super! Funktioniert bei mir tadellos. Danke! LG, Tobi

**Comment by phoebusryan** [comment]
Danke, die gefixte Version ist nun im Installer.

**Comment by TobiasKrais** [comment]
Danke dir für die schnelle Reaktion! Funktioniert perfekt!
