### ISSUE TITLE
decryptUnicorn is not defined

### ISSUE THREAD

**Issue by ceekay82** [FriendsOfREDAXO/emailobfuscator#8]
Beim Klick auf einen E-Mail-Link passiert nichts. In der Konsole steht der Fehler: "decryptUnicorn is not defined" Windows 8.1 Chrome, Firefox und IE 11.  Nicht eingeloggt im Backend. Keine Templates oder Kategorien ausgeschlossen.

**Comment by phoebusryan** [comment]
Ja, da fehlen wohl die Files. Diese müssen eingebunden werden:
https://github.com/FriendsOfREDAXO/rex_emailobfuscator

**Comment by ceekay82** [comment]
Danke! Ich hatte den Vorgänger für Rex4 viel im Einsatz - da brauchte man das nicht. Den Hinweis mit den CSS und JS-DAtein könnte man vielleicht bei einer Hilfeseite mit bei der Konfiguration mit aufnehmen.

**Comment by phoebusryan** [comment]
Es steht in der Addon-Hilfe und hier auf Github. Das sollte reichen.

Die Version von R4 funktioniert ganz anders und ist nicht von mir. Ich hab es so gelöst, weil man flexibler ist.
