### ISSUE TITLE
Addon-Name: `rex_`-Prefix entfernen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/emailobfuscator#9]
Der Konsens bei FOR ist, keine Prefixe zu verwenden. Bei einem bereits veröffentlichten Addon ist der Wechsel allerdings mit etwas Aufwand verbunden:
1. Prüfen, ob der neue Addon-Key verfügbar ist
2. Addon mit neuem Key bei MyREDAXO anlegen
3. Repo umbenennen
4. Alte Bezeichnung im gesamten Addon auf neue wechseln
5. Neues Major-Release veröffentlichen mit Hinweis auf neuen Namen
6. Ggfls Hinweis im Forum hinterlassen, denn Nutzer des alten Addons kriegen im Installer keinen Hinweis auf Updates mehr

**Comment by schuer** [comment]
Diskussion im Slack: Die Umbenennung soll erst nach Fertigstellung der neuen Website angegangen werden. Bei der Integration wird es dann vermutlich bessere Möglichkeiten geben als jetzt.

**Comment by phoebusryan** [comment]
https://github.com/redaxo/redaxo/issues/814

**Comment by schuer** [comment]
Jetzt kommen ja ein paar PRs, und bei der Gelegenheit könnten wir das Addon unbenennen.

Den genauen Workflow müssen wir noch mit @gharlan besprechen. Eventuell kann ein Alias eingerichtet werden.

**Comment by phoebusryan** [comment]
Lass uns damit einfach warten bis die neue Webseite da ist:
https://github.com/redaxo/redaxo/issues/814

**Comment by schuer** [comment]
Ich möchte leider nochmal öffnen, sonst kommen wir mit dem Thema nicht weiter.

Die Situation ist, dass es aktuell vermutlich an Kapazitäten fehlt, das Feature (redaxo/redaxo#814) im Zuge der neuen Website umzusetzen. Eventuell wird es eine schlichte Alias-Lösung geben, die manuell von den REX-Admins eingerichtet werden muss, vielleicht aber reicht es selbst dafür aktuell nicht, denn es gibt so viele wichtigere Themen.
Letztendlich ist das auch ziemlich viel Arbeit für eher geringen Nutzen: Es wird wohl nicht allzu häufig vorkommen, dass Addons umbenannt werden müssen.

Jedenfalls, ich würde gerne die Chance gerne nutzen, und dieses Addon hier manuell umbenennen. Eben damit wir die blöden rex-Prefixe nicht noch ewig mit uns rumtragen.

Vorschlag des Workflows:
1. Neuen Addon-Key anmelden und Git-Repo auf neuen Key umbenennen (Hier z. B.: `email-obfuscator`).
2. Im Repo einen neuen Branch erstellen, der wie der alte Key heißt. Darin das Addon um die Info der Umbenennung erweitern und ein letztes Release veröffentlichen.
3. Major-Release unter neuem Key veröffentlichen.

Was bedeutet das für Nutzer?
1. Sie sehen im Installer, dass das Addon unter aktuellem Namen nicht fortgeführt wird. Es gibt ein letztes Update, das auf den neuen Namen hinweist.
2. Sie müssen das neue Addon installieren und ggfls. die Konfiguration übertragen.
3. Sie müssen Vorkommen von `rex_addon::get(…)->isAvailable()` und ähnliche Dinge auf den neuen Namen anpassen. Am besten also einmal global durch den Code suchen und ersetzen.

Was sonst noch?
- Im Addon-Verzeichnis auf redaxo.org wird es doppelte Addons geben. Alter Name und neuer Name. Die alten könnten wir allerdings irgendwann ausknipsen, wenn es einen Alias gibt.
- Bei Github wird es keine doppelten Repos geben, wenn wir wie oben beschrieben mit Branches arbeiten.

**Nochmal in die Runde gefragt: Wollen wir das jetzt beim Email-Obfuscator mal machen? Ich bin sehr dafür und kann mich auch gerne drum kümmern.**

**Comment by joachimdoerr** [comment]
Raus mit dem albernen Prefix. Finde es gut, dass du das vorantreibst.

**Comment by skerbis** [comment]
Die Anzahl der Addons, die betroffen sind ist ja überschaubar. Denke, dass es da kaum zu Problemen kommen wird.

**Comment by schuer** [comment]
Erledigt, siehe auch Slack-Diskussion.

Fazit: War jetzt erstmalig deutlich aufwendiger als geplant, was aber vor allem daran lag, dass die Updatehinweise verfasst werden mussten. Alle zukünftigen Addon-Umbenennungen sollten hoffentlich in 30 Minuten pro Addon erledigt sein.
